### ISSUE TITLE
strings are evil

### ISSUE THREAD

**Issue by Bartolomeus-649** [littledan/proposal-built-in-decorators#5]
Any way of avoiding string literals in declarations?

```
const Point = new StructType([
  { name: "x", type: float64 },
  { name: "y", type: float64 }
]);
```

_imo, strings should only be used when there is a need to "display" human readable text to an en user._

**Comment by nicolo-ribaudo** [comment]
How is it related to this proposal?

**Comment by ljharb** [comment]
Isn’t a name human-readable text for end users?

**Comment by littledan** [comment]
Closing, as the concern seems to be unrelated to this proposal.
